# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d67ded19540525aa1e4b7fd309b37225b7291d611a3c6c324ee8d8741f63a813a3df46d32843e0bdcc29213c19eadec7c3c8d7a149a05ce46a348a5eaae5a308

test:
  secret_key_base: 936f85aab47e9b7d53d8e6fe3d510e8a9f90d226137d84a07dd1de2f83bd1271d383c8ffd9737600c41443b376f8cc93c57c8cba049c6113e09f7302d5801a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
